name: Prime Hunt Data Pipeline

on:
  schedule:
    - cron: "0 0 * * *"
    
  workflow_dispatch:

jobs:

  update:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build

      - name: Update Relics
        run: ./gradlew relics

      - name: Update Prime Sets
        run: ./gradlew prime_sets

      - name: Update Prime Collections
        run: ./gradlew prime_collections

      - name: Update Manifest
        run: ./gradlew manifest

      - name: Check database consistency
        run: ./gradlew consistency

      - name: Commit updated JSONs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore(data): update generated database"
            git push
          fi
