name: Prime Hunt Data Pipeline

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:

  relics:

    name: Update Relics
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - run: chmod +x gradlew

      - name: Execute Relics Pipeline
        run: ./gradlew relics

      - name: Upload Relics
        uses: actions/upload-artifact@v4
        with:
          name: relics
          path: data/relics.json

  prime_sets:

    name: Update Prime Sets
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - run: chmod +x gradlew

      - name: Execute Prime Sets Pipeline
        run: ./gradlew prime_sets

      - name: Upload Prime Sets
        uses: actions/upload-artifact@v4
        with:
          name: prime_sets
          path: data/prime-sets.json

  prime_collections:

    name: Update Prime Collections
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - run: chmod +x gradlew

      - name: Execute Prime Collections Pipeline
        run: ./gradlew prime_collections

      - name: Upload Prime Collections
        uses: actions/upload-artifact@v4
        with:
          name: prime_collections
          path: data/prime-collections.json

  manifest:

    name: Update Manifest

    needs:
      - relics
      - prime_sets
      - prime_collections

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - run: chmod +x gradlew

      - uses: actions/download-artifact@v4
        with:
          name: relics
          path: data

      - uses: actions/download-artifact@v4
        with:
          name: prime_sets
          path: data

      - uses: actions/download-artifact@v4
        with:
          name: prime_collections
          path: data

      - name: Execute Manifest Pipeline
        run: ./gradlew manifest

      - name: Upload Manifest
        uses: actions/upload-artifact@v4
        with:
          name: manifest
          path: data/manifest.json

  consistency:

    name: Validate Database

    needs:
      - manifest

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - run: chmod +x gradlew

      - uses: actions/download-artifact@v4
        with:
          name: relics
          path: data

      - uses: actions/download-artifact@v4
        with:
          name: prime_sets
          path: data

      - uses: actions/download-artifact@v4
        with:
          name: prime_collections
          path: data

      - uses: actions/download-artifact@v4
        with:
          name: manifest
          path: data

      - name: Execute Consistency Pipeline
        run: ./gradlew consistency

      - name: Upload Validated Database
        uses: actions/upload-artifact@v4
        with:
          name: validated_database
          path: data/

  commit:

    name: Publish Database

    needs:
      - consistency

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: validated_database
          path: .

      - name: Commit Changes
        run: |

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data
          
      - name: Debug
        run: |
          git status
          git diff

          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          git commit -m "chore(data): update generated database"

          git push